#!/bin/bash

# Check if arguments are provided
if [ $# -ne 2 ] && [ $# -ne 3 ]; then
    echo "Usage: $0 <file_path> <desired_line> [comment]"
    exit 1
fi

file_path="$1"
desired_line="$2"
# Newline only if commant isn't empty
if [ $# -eq 3 ]; then
    comment="$3\n"
else
    comment=""
fi


# Check if file exists
if [ -f "$file_path" ]; then
    # Check if the line doesn't exist
    if grep -qF "$desired_line" "$file_path"; then
        echo "Config '$file_path': '$desired_line' already exists."
    else
        # If the line doesn't exist, append a \newline and the line to the end.
        echo -e "$comment""$desired_line"'\n' >> "$file_path"
        echo "Config '$file_path': '$desired_line' added."
    fi
else
    echo "INFO: '$file_path' doesn't exist."
    echo -e "$comment""$desired_line"'\n' > "$file_path"
    echo "Config '$file_path': '$desired_line' added to a new file."
fi

