#!/bin/bash

# Check if arguments are provided
if [ $# -ne 2 ]; then
    echo "Usage: $0 <file_path> <desired_line>"
    exit 1
fi

file_path="$1"
desired_line="$2"


# Check if file exists
if [ -f "$file_path" ]; then
    # Check if the line doesn't exist
    if grep -qF "$desired_line" "$file_path"; then
        echo "Config '$file_path': '$desired_line' already exists."
    else
        # If the line doesn't exist, append a \newline and the line to the end.
        echo "\n$desired_line" >> "$file_path"
        echo "Config '$file_path': '$desired_line' added."
    fi
else
    echo "Error: '$desired_line' couldn't be added, $file_path doesn't exist"
fi

